export const tokens = {
  colors: {
    appBg: '#ececef',
    surface: '#f5f5f6',
    card: '#ffffff',
    text: '#222222',
    muted: '#8b8b95',
    border: '#e7e7eb',
    vendorPrimary: '#ff7a1a',
    vendorPrimaryDark: '#f56a00',
    vendorSoft: '#fff2e8',
    success: '#28c66f',
    successSoft: '#e7faef',
    danger: '#ff5a55',
    dangerSoft: '#ffecea',
    warningSoft: '#fff2e1',
    deliveryPrimary: '#5f6df7',
    deliveryPrimaryDark: '#4656dc',
    deliverySoft: '#edf0ff',
    darkPill: '#34363d',
    inputBg: '#f2f2f4',
  },
  radius: {
    xs: 10,
    sm: 14,
    md: 18,
    lg: 24,
    xl: 32,
    round: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
  },
} as const;
